// ISO 4217 currency code → human-readable name. Top ~50 most common world
// currencies plus a few extras the open.er-api.com EUR feed routinely returns.
// `getCurrencyName(code)` falls back to the raw code if not in the map, so
// unknown codes still display safely in the selector.
export const CURRENCY_NAMES: Record<string, string> = {
  EUR: "Euro",
  USD: "US Dollar",
  GBP: "British Pound",
  JPY: "Japanese Yen",
  CNY: "Chinese Yuan",
  CHF: "Swiss Franc",
  CAD: "Canadian Dollar",
  AUD: "Australian Dollar",
  NZD: "New Zealand Dollar",
  SEK: "Swedish Krona",
  NOK: "Norwegian Krone",
  DKK: "Danish Krone",
  PLN: "Polish Złoty",
  CZK: "Czech Koruna",
  HUF: "Hungarian Forint",
  RON: "Romanian Leu",
  BGN: "Bulgarian Lev",
  HRK: "Croatian Kuna",
  ISK: "Icelandic Króna",
  TRY: "Turkish Lira",
  RUB: "Russian Ruble",
  UAH: "Ukrainian Hryvnia",
  ALL: "Albanian Lek",
  MKD: "Macedonian Denar",
  BAM: "Bosnia-Herzegovina Mark",
  RSD: "Serbian Dinar",
  MDL: "Moldovan Leu",
  GEL: "Georgian Lari",
  MXN: "Mexican Peso",
  BRL: "Brazilian Real",
  ARS: "Argentine Peso",
  COP: "Colombian Peso",
  CLP: "Chilean Peso",
  PEN: "Peruvian Sol",
  KRW: "South Korean Won",
  HKD: "Hong Kong Dollar",
  SGD: "Singapore Dollar",
  TWD: "Taiwan Dollar",
  THB: "Thai Baht",
  IDR: "Indonesian Rupiah",
  MYR: "Malaysian Ringgit",
  PHP: "Philippine Peso",
  VND: "Vietnamese Đồng",
  INR: "Indian Rupee",
  PKR: "Pakistani Rupee",
  BDT: "Bangladeshi Taka",
  LKR: "Sri Lankan Rupee",
  NPR: "Nepalese Rupee",
  AED: "UAE Dirham",
  SAR: "Saudi Riyal",
  QAR: "Qatari Riyal",
  KWD: "Kuwaiti Dinar",
  BHD: "Bahraini Dinar",
  ILS: "Israeli Shekel",
  EGP: "Egyptian Pound",
  JOD: "Jordanian Dinar",
  ZAR: "South African Rand",
  NGN: "Nigerian Naira",
  KES: "Kenyan Shilling",
  GHS: "Ghanaian Cedi",
  MAD: "Moroccan Dirham",
};

export function getCurrencyName(code: string): string {
  return CURRENCY_NAMES[code] ?? code;
}
